"""
Inserta DobleUnidadLoteModal antes de 'export default function Autoventa() {'
"""

path = r'C:\PANELDECONTROLV3\frontend\src\pages\autoventa\Autoventa.tsx'
with open(path, 'rb') as f:
    content = f.read()

marker = b'export default function Autoventa() {'
pos = content.find(marker)
print(f'Marker found at byte position: {pos}')

new_component = (
    b'// -- Doble Unidad + Lote Modal ------------------------------------------\r\n'
    b'\r\n'
    b'function DobleUnidadLoteModal({\r\n'
    b'    nombre,\r\n'
    b'    referencia,\r\n'
    b'    unidadNombre,\r\n'
    b'    lotes,\r\n'
    b'    initialUds,\r\n'
    b'    onConfirm,\r\n'
    b'    onClose,\r\n'
    b'}: {\r\n'
    b'    nombre: string\r\n'
    b'    referencia: string\r\n'
    b'    unidadNombre: string\r\n'
    b'    lotes: Lote[]\r\n'
    b'    initialUds: string\r\n'
    b'    onConfirm: (uds: string, asignaciones: AsignacionLote[]) => void\r\n'
    b'    onClose: () => void\r\n'
    b'}) {\r\n'
    b'    const [uds, setUds] = useState(initialUds === \'0\' ? \'\' : initialUds)\r\n'
    b'    const [asignaciones, setAsignaciones] = useState<AsignacionLote[]>(() =>\r\n'
    b'        lotes.map(l => ({ id: l.id, lote: l.lote, fecha_caducidad: l.fecha_caducidad, stock: l.stock, asignar: 0 }))\r\n'
    b'    )\r\n'
    b'    const udsRef = useRef<HTMLInputElement>(null)\r\n'
    b'    useEffect(() => { udsRef.current?.focus() }, [])\r\n'
    b'\r\n'
    b'    const totalKilos = asignaciones.reduce((s, a) => s + a.asignar, 0)\r\n'
    b'    const stockTotal = lotes.reduce((s, l) => s + l.stock, 0)\r\n'
    b'    const udsNum = parseFloat(uds) || 0\r\n'
    b'    const ok = udsNum > 0 && totalKilos > 0\r\n'
    b'\r\n'
    b'    const updateAsignacion = (idx: number, val: string) => {\r\n'
    b'        const n = Math.max(0, Math.round((parseFloat(val) || 0) * 100) / 100)\r\n'
    b'        setAsignaciones(prev => prev.map((a, i) => i === idx ? { ...a, asignar: n } : a))\r\n'
    b'    }\r\n'
    b'\r\n'
    b'    const fmtKg = (v: number) => v.toLocaleString(\'es-ES\', { minimumFractionDigits: 2, maximumFractionDigits: 2 })\r\n'
    b'    const fmtDate = (d: string | null) =>\r\n'
    b'        d ? new Date(d).toLocaleDateString(\'es-ES\', { day: \'2-digit\', month: \'2-digit\', year: \'2-digit\' }) : \'--\'\r\n'
    b'\r\n'
    b'    return (\r\n'
    b'        <div className="fixed inset-0 bg-black/50 z-[70] flex items-center justify-center px-3" onClick={onClose}>\r\n'
    b'            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm max-h-[90vh] flex flex-col" onClick={e => e.stopPropagation()}>\r\n'
    b'                {/* Header */}\r\n'
    b'                <div className="flex items-center justify-between px-4 py-3 border-b border-slate-200">\r\n'
    b'                    <div className="flex items-center gap-2">\r\n'
    b'                        <Package className="w-4 h-4 text-amber-600" />\r\n'
    b'                        <div>\r\n'
    b'                            <p className="text-sm font-bold text-slate-800 leading-tight">{nombre}</p>\r\n'
    b'                            <p className="text-[10px] text-slate-400 font-mono">{referencia}</p>\r\n'
    b'                            <span className="text-[10px] text-teal-600 font-semibold">Doble unidad \xc2\xb7 {unidadNombre}</span>\r\n'
    b'                        </div>\r\n'
    b'                    </div>\r\n'
    b'                    <button onClick={onClose} className="p-1 rounded hover:bg-slate-100"><X className="w-4 h-4 text-slate-500" /></button>\r\n'
    b'                </div>\r\n'
    b'                {/* Unidades */}\r\n'
    b'                <div className="px-4 py-3 border-b border-slate-100">\r\n'
    b'                    <label className="text-xs font-semibold text-slate-600 block mb-1">Unidades</label>\r\n'
    b'                    <input\r\n'
    b'                        ref={udsRef}\r\n'
    b'                        type="number" min="0" step="0.001" inputMode="decimal"\r\n'
    b'                        className="w-full text-right text-lg font-bold border border-slate-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-brand"\r\n'
    b'                        value={uds} placeholder="0"\r\n'
    b'                        onChange={e => setUds(e.target.value)}\r\n'
    b'                    />\r\n'
    b'                </div>\r\n'
    b'                {/* Cabecera lotes */}\r\n'
    b'                <div className="px-4 pt-2 pb-1 border-b border-slate-100">\r\n'
    b'                    <p className="text-xs font-semibold text-slate-600">\r\n'
    b'                        {unidadNombre} por lote\r\n'
    b'                        <span className="ml-2 text-slate-400 font-normal">Stock total: {fmtKg(stockTotal)} {unidadNombre}</span>\r\n'
    b'                    </p>\r\n'
    b'                </div>\r\n'
    b'                {/* Lista de lotes */}\r\n'
    b'                <div className="overflow-y-auto flex-1 divide-y divide-slate-100">\r\n'
    b'                    {lotes.length === 0 ? (\r\n'
    b'                        <p className="text-sm text-slate-400 text-center py-6">Sin lotes con stock</p>\r\n'
    b'                    ) : asignaciones.map((a, idx) => (\r\n'
    b'                        <div key={a.id} className="px-4 py-2.5">\r\n'
    b'                            <div className="flex items-center justify-between mb-1">\r\n'
    b'                                <div>\r\n'
    b'                                    <span className="text-sm font-semibold text-slate-800 font-mono">{a.lote}</span>\r\n'
    b'                                    {a.fecha_caducidad && (\r\n'
    b'                                        <span className={`ml-2 text-xs px-1.5 py-0.5 rounded-full font-medium ${new Date(a.fecha_caducidad) < new Date() ? \'bg-red-100 text-red-700\' : \'bg-amber-50 text-amber-700\'}`}>\r\n'
    b'                                            Cad. {fmtDate(a.fecha_caducidad)}\r\n'
    b'                                        </span>\r\n'
    b'                                    )}\r\n'
    b'                                </div>\r\n'
    b'                                <span className="text-xs text-slate-400">Stk: {fmtKg(a.stock)}</span>\r\n'
    b'                            </div>\r\n'
    b'                            <div className="flex items-center gap-2">\r\n'
    b'                                <label className="text-xs text-teal-600 font-semibold w-20">{unidadNombre}:</label>\r\n'
    b'                                <input\r\n'
    b'                                    type="number" min="0" step="0.01" max={a.stock} inputMode="decimal"\r\n'
    b'                                    className="input text-right text-sm flex-1"\r\n'
    b'                                    value={a.asignar === 0 ? \'\' : a.asignar}\r\n'
    b'                                    placeholder="0.00"\r\n'
    b'                                    onChange={e => updateAsignacion(idx, e.target.value)}\r\n'
    b'                                />\r\n'
    b'                                <span className="text-xs text-slate-400">/ {fmtKg(a.stock)}</span>\r\n'
    b'                            </div>\r\n'
    b'                        </div>\r\n'
    b'                    ))}\r\n'
    b'                </div>\r\n'
    b'                {/* Footer */}\r\n'
    b'                <div className="px-4 py-3 border-t border-slate-200 space-y-2">\r\n'
    b'                    <div className="flex justify-between text-sm">\r\n'
    b'                        <span className="text-slate-500">Total {unidadNombre}:</span>\r\n'
    b'                        <span className={`font-bold ${totalKilos > 0 ? \'text-teal-600\' : \'text-slate-400\'}`}>{fmtKg(totalKilos)}</span>\r\n'
    b'                    </div>\r\n'
    b'                    <button\r\n'
    b'                        onClick={() => onConfirm(uds || \'0\', asignaciones.filter(a => a.asignar > 0))}\r\n'
    b'                        disabled={!ok}\r\n'
    b'                        className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-40"\r\n'
    b'                    >\r\n'
    b'                        <Check className="w-4 h-4" /> Confirmar\r\n'
    b'                    </button>\r\n'
    b'                </div>\r\n'
    b'            </div>\r\n'
    b'        </div>\r\n'
    b'    )\r\n'
    b'}\r\n'
    b'\r\n'
)

new_content = content[:pos] + new_component + content[pos:]
with open(path, 'wb') as f:
    f.write(new_content)
print(f'Done. Old size: {len(content)}, New size: {len(new_content)}, Added: {len(new_content) - len(content)} bytes')
